server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# - job_name: system
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log
# - job_name: docker
#   static_configs:
#     - targets:
#         - localhost
#       labels:
#         job: docker_logs
#         __path__: /var/lib/docker/containers/*/*-json.log
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      # filters:
      #   - name: label
      #     values: ["logging=promtail"]
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    - source_labels: ['__meta_docker_container_log_stream']
      target_label: 'logstream'
    - source_labels: ['__meta_docker_container_label_logging_jobname']
      target_label: 'job'
  pipeline_stages:
    - docker: {}
- job_name: plex
  static_configs:
    - labels:
        __path__: /plexlogs/*.log
        job: plex
  pipeline_stages:
    - regex:
        expression: "^(?s)(?P<time>\\w+ \\d+, \\d+ \\d+:\\d+:\\d+\\.\\d+?) \\[(?P<epoch>[^\\]]+)\\] (?P<level>[a-zA-Z]+) - (?P<content>.*)$"
    - labels:
        level:
        content:
    - timestamp:
        source: time
        format: "Jan 02, 2006 15:04:05.000"
        location: "Etc/UTC"
    - output:
        source: content